CREATE DATABASE NotificationDB;

USE NotificationDB;

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    PlanId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL
);